version: "3.1"

services:
  db:
    container_name: db-psql
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/aplicacao
    ports:
      - "3000:3000"
    depends_on:
      - db