version: "3.1"

services:
  db:
    container_name: db-psql
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTRES_USER: postgres
      POSTGRES_PASSWORD: postgres
