version: "3.1"

services:
  db:
    container_name: db-psql
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  app:
    container_name: app
    build:
      context: .
      dockerfile: app.Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    depends_on:
      - app
    ports:
      - 80:80

